###Create vehicle report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make":"Ford",
    "model":"Mustang",
    "year":1982,
    "mileage":50000,
    "lng":45,
    "lat":45,
    "price":20000
}

###Aprove a report with given id
PATCH http://localhost:3000/reports/7
Content-Type: application/json

{
    "approved":true
}

###Get Estimate
GET http://localhost:3000/reports?make=Ford&model=Mustang&lng=45&lat=45&mileage=20000&year=1981
